obj-m := x86-64-asterfusion-cx308p-48y-n_fl00e03.o
x86-64-asterfusion-cx308p-48y-n_fl00e03-y := x86-64-asterfusion-cx308p-48y-n-common.o x86-64-asterfusion-cx308p-48y-n-eeprom.o x86-64-asterfusion-cx308p-48y-n-power.o \
x86-64-asterfusion-cx308p-48y-n-fan.o x86-64-asterfusion-cx308p-48y-n-sfp.o x86-64-asterfusion-cx308p-48y-n-thermal.o x86-64-asterfusion-cx308p-48y-n-sys.o