# name              lanes          alias         speed       index   mtu      fec
Ethernet1           0              Y1            25000       0       9126     none
Ethernet2           1              Y2            25000       1       9126     none
Ethernet3           2              Y3            25000       2       9126     none
Ethernet4           3              Y4            25000       3       9126     none
Ethernet5           4              Y5            25000       4       9126     none
Ethernet6           5              Y6            25000       5       9126     none
Ethernet7           6              Y7            25000       6       9126     none
Ethernet8           7              Y8            25000       7       9126     none
Ethernet9           8              Y9            25000       8       9126     none
Ethernet10          9              Y10           25000       9       9126     none
Ethernet11          10             Y11           25000       10      9126     none
Ethernet12          11             Y12           25000       11      9126     none
Ethernet13          12             Y13           25000       12      9126     none
Ethernet14          13             Y14           25000       13      9126     none
Ethernet15          14             Y15           25000       14      9126     none
Ethernet16          15             Y16           25000       15      9126     none
Ethernet17          16             Y17           25000       16      9126     none
Ethernet18          17             Y18           25000       17      9126     none
Ethernet19          18             Y19           25000       18      9126     none
Ethernet20          19             Y20           25000       19      9126     none
Ethernet21          20             Y21           25000       20      9126     none
Ethernet22          21             Y22           25000       21      9126     none
Ethernet23          22             Y23           25000       22      9126     none
Ethernet24          23             Y24           25000       23      9126     none
Ethernet25          24             Y25           25000       24      9126     none
Ethernet26          25             Y26           25000       25      9126     none
Ethernet27          26             Y27           25000       26      9126     none
Ethernet28          27             Y28           25000       27      9126     none
Ethernet29          28             Y29           25000       28      9126     none
Ethernet30          29             Y30           25000       29      9126     none
Ethernet31          30             Y31           25000       30      9126     none
Ethernet32          31             Y32           25000       31      9126     none
Ethernet33          32             Y33           25000       32      9126     none
Ethernet34          33             Y34           25000       33      9126     none
Ethernet35          34             Y35           25000       34      9126     none
Ethernet36          35             Y36           25000       35      9126     none
Ethernet37          36             Y37           25000       36      9126     none
Ethernet38          37             Y38           25000       37      9126     none
Ethernet39          38             Y39           25000       38      9126     none
Ethernet40          39             Y40           25000       39      9126     none
Ethernet41          40             Y41           25000       40      9126     none
Ethernet42          41             Y42           25000       41      9126     none
Ethernet43          42             Y43           25000       42      9126     none
Ethernet44          43             Y44           25000       43      9126     none
Ethernet45          44             Y45           25000       44      9126     none
Ethernet46          45             Y46           25000       45      9126     none
Ethernet47          46             Y47           25000       46      9126     none
Ethernet48          47             Y48           25000       47      9126     none
Ethernet49          48,49,50,51    C1            100000      48      9126     rs
Ethernet53          52,53,54,55    C2            100000      49      9126     rs
Ethernet57          56,57,58,59    C3            100000      50      9126     rs
Ethernet61          64,65,66,67    C4            100000      51      9126     rs
Ethernet65          68,69,70,71    C5            100000      52      9126     rs
Ethernet69          72,73,74,75    C6            100000      53      9126     rs
Ethernet73          76,77,78,79    C7            100000      54      9126     rs
Ethernet77          80,81,82,83    C8            100000      55      9126     rs
