#  name       alias          lanes    index         speed   autoneg  fec    media_type  default_vlan
Ethernet1     Ethernet1          0        0             1000    0       none    copper   1 
Ethernet2     Ethernet2          1        1             1000    0       none    copper   1
Ethernet3     Ethernet3          2        2             1000    0       none    copper   1
Ethernet4     Ethernet4          3        3             1000    0       none    copper   1
Ethernet5     Ethernet5          4        4             1000    0       none    copper   1
Ethernet6     Ethernet6          5        5             1000    0       none    copper   1
Ethernet7     Ethernet7          6        6             1000    0       none    copper   1
Ethernet8     Ethernet8          7        7             1000    0       none    copper   1
Ethernet9     Ethernet9          8        8             1000    0       none    copper   1
Ethernet10    Ethernet10         9        9             1000    0       none    copper   1
Ethernet11    Ethernet11         10       10            1000    0       none    copper   1
Ethernet12    Ethernet12         11       11            1000    0       none    copper   1
Ethernet13    Ethernet13         12       12            1000    0       none    copper   1
Ethernet14    Ethernet14         13       13            1000    0       none    copper   1
Ethernet15    Ethernet15         14       14            1000    0       none    copper   1
Ethernet16    Ethernet16         15       15            1000    0       none    copper   1
Ethernet17    Ethernet17         18       16            10000   0       none    fiber    1
Ethernet18    Ethernet18         19       17            10000   0       none    fiber    1 
Ethernet19    InnerEth1          16       18            10000   0       none    fiber    1
