onie_arch=aarch64
onie_build_platform=aarch64-r0
onie_config_version=1
onie_dev=/dev/sdb2
onie_firmware=auto
onie_grub_image_name=grubaa64.efi
onie_initrd_tmp=/
onie_kernel_version=5.10.34-103
onie_machine=arm64
onie_machine_rev=0
onie_partition_type=gpt
onie_platform=arm64-asterfusion_cx204y_48gt_a-r0
onie_root_dir=/mnt/onie-boot/onie
onie_secure_boot=yes
onie_skip_ethmgmt_macs=yes
onie_switch_asic=marvell
onie_uefi_arch=aa64
onie_uefi_boot_loader=grubaa64.efi
onie_vendor_id=42623