#!/bin/sh

mr_reboot() {

    # sudo rmmod x86-64-asterfusion-cx308p-48y-n
    # sudo /usr/bin/bmc_get 0x0a 0xa1 0xaa
    sudo /sbin/reboot &
    sleep 120
    echo "Shutdown is timed out, force reboot!"
    sudo echo b > /proc/sysrq-trigger
}

if [ $# -eq 0 ] || [ $@ = "-f" ] || [ $@ = "--force" ] || [ $@ = "reboot" ]; then
    mr_reboot
elif [ $@ = "-p" ] ; then
    sudo halt
else
    echo "unsupported option"
fi
