#  name                 lanes    index         speed   autoneg  fec
Ethernet1               0        0             1000    0       none    
Ethernet2               1        1             1000    0       none    
Ethernet3               2        2             1000    0       none    
Ethernet4               3        3             1000    0       none    
Ethernet5               4        4             1000    0       none    
Ethernet6               5        5             1000    0       none    
Ethernet7               6        6             1000    0       none    
Ethernet8               7        7             1000    0       none    
Ethernet9               8        8             1000    0       none    
Ethernet10              9        9             1000    0       none    
Ethernet11              10       10            1000    0       none    
Ethernet12              11       11            1000    0       none    
Ethernet13              12       12            1000    0       none    
Ethernet14              13       13            1000    0       none    
Ethernet15              14       14            1000    0       none    
Ethernet16              15       15            1000    0       none    
Ethernet17              16       16            1000    0       none    
Ethernet18              17       17            1000    0       none    
Ethernet19              18       18            1000    0       none    
Ethernet20              19       19            1000    0       none    
Ethernet21              20       20            1000    0       none    
Ethernet22              21       21            1000    0       none    
Ethernet23              22       22            1000    0       none    
Ethernet24              23       23            1000    0       none    
Ethernet25              24       24            1000    0       none    
Ethernet26              25       25            1000    0       none    
Ethernet27              26       26            1000    0       none    
Ethernet28              27       27            1000    0       none    
Ethernet29              28       28            1000    0       none    
Ethernet30              29       29            1000    0       none    
Ethernet31              30       30            1000    0       none    
Ethernet32              31       31            1000    0       none    
Ethernet33              32       32            1000    0       none    
Ethernet34              33       33            1000    0       none    
Ethernet35              34       34            1000    0       none    
Ethernet36              35       35            1000    0       none    
Ethernet37              36       36            1000    0       none    
Ethernet38              37       37            1000    0       none    
Ethernet39              38       38            1000    0       none    
Ethernet40              39       39            1000    0       none    
Ethernet41              40       40            1000    0       none    
Ethernet42              41       41            1000    0       none    
Ethernet43              42       42            1000    0       none    
Ethernet44              43       43            1000    0       none    
Ethernet45              44       44            1000    0       none    
Ethernet46              45       45            1000    0       none    
Ethernet47              46       46            1000    0       none    
Ethernet48              47       47            1000    0       none    
Ethernet49              50       48            25000    0       none   
Ethernet50              51       49            25000    0       none   
Ethernet51              52       50            25000    0       none   
Ethernet52              53       51            25000    0       none   