#  name       alias       lanes    index         speed   autoneg  fec    media_type
Ethernet1     Ethernet1          0        0             1000    0       none    copper
Ethernet2     Ethernet2          1        1             1000    0       none    copper
Ethernet3     Ethernet3          2        2             1000    0       none    copper
Ethernet4     Ethernet4          3        3             1000    0       none    copper
Ethernet5     Ethernet5          4        4             1000    0       none    copper
Ethernet6     Ethernet6          5        5             1000    0       none    copper
Ethernet7     Ethernet7          6        6             1000    0       none    copper
Ethernet8     Ethernet8          7        7             1000    0       none    copper
Ethernet9     Ethernet9          8        8             1000    0       none    copper
Ethernet10    Ethernet10         9        9             1000    0       none    copper
Ethernet11    Ethernet11         10       10            1000    0       none    copper
Ethernet12    Ethernet12         11       11            1000    0       none    copper
Ethernet13    Ethernet13         12       12            1000    0       none    copper
Ethernet14    Ethernet14         13       13            1000    0       none    copper
Ethernet15    Ethernet15         14       14            1000    0       none    copper
Ethernet16    Ethernet16         15       15            1000    0       none    copper
Ethernet17    Ethernet17         16       16            1000    0       none    copper
Ethernet18    Ethernet18         17       17            1000    0       none    copper
Ethernet19    Ethernet19         18       18            1000    0       none    copper
Ethernet20    Ethernet20         19       19            1000    0       none    copper
Ethernet21    Ethernet21         20       20            1000    0       none    copper
Ethernet22    Ethernet22         21       21            1000    0       none    copper
Ethernet23    Ethernet23         22       22            1000    0       none    copper
Ethernet24    Ethernet24         23       23            1000    0       none    copper
Ethernet25    Ethernet25         24       24            1000    0       none    copper
Ethernet26    Ethernet26         25       25            1000    0       none    copper
Ethernet27    Ethernet27         26       26            1000    0       none    copper
Ethernet28    Ethernet28         27       27            1000    0       none    copper
Ethernet29    Ethernet29         28       28            1000    0       none    copper
Ethernet30    Ethernet30         29       29            1000    0       none    copper
Ethernet31    Ethernet31         30       30            1000    0       none    copper
Ethernet32    Ethernet32         31       31            1000    0       none    copper
Ethernet33    Ethernet33         32       32            1000    0       none    copper
Ethernet34    Ethernet34         33       33            1000    0       none    copper
Ethernet35    Ethernet35         34       34            1000    0       none    copper
Ethernet36    Ethernet36         35       35            1000    0       none    copper
Ethernet37    Ethernet37         36       36            1000    0       none    copper
Ethernet38    Ethernet38         37       37            1000    0       none    copper
Ethernet39    Ethernet39         38       38            1000    0       none    copper
Ethernet40    Ethernet40         39       39            1000    0       none    copper
Ethernet41    Ethernet41         40       40            1000    0       none    copper
Ethernet42    Ethernet42         41       41            1000    0       none    copper
Ethernet43    Ethernet43         42       42            1000    0       none    copper
Ethernet44    Ethernet44         43       43            1000    0       none    copper
Ethernet45    Ethernet45         44       44            1000    0       none    copper
Ethernet46    Ethernet46         45       45            1000    0       none    copper
Ethernet47    Ethernet47         46       46            1000    0       none    copper
Ethernet48    Ethernet48         47       47            1000    0       none    copper
Ethernet49    Ethernet49         48       48            25000    0       none    fiber
Ethernet50    Ethernet50         49       49            25000    0       none    fiber
Ethernet51    Ethernet51         50       50            25000    0       none    fiber
Ethernet52    Ethernet52         51       51            25000    0       none    fiber
Ethernet53    Ethernet53         52       52            25000    0       none    fiber
Ethernet54    Ethernet54         53       53            25000    0       none    fiber
