# name            lanes         speed       index     autoneg  fec
Ethernet1         46            10000        0         0        none
Ethernet2         47            10000        1         0        none
Ethernet3         44            10000        2         0        none
Ethernet4         45            10000        3         0        none
Ethernet5         42            10000        4         0        none
Ethernet6         43            10000        5         0        none
Ethernet7         40            10000        6         0        none
Ethernet8         41            10000        7         0        none
Ethernet9         38            10000        8         0        none
Ethernet10        39            10000        9         0        none
Ethernet11        36            10000        10        0        none
Ethernet12        37            10000        11        0        none
Ethernet13        34            10000        12        0        none
Ethernet14        35            10000        13        0        none
Ethernet15        32            10000        14        0        none
Ethernet16        33            10000        15        0        none
Ethernet17        30            10000        16        0        none
Ethernet18        31            10000        17        0        none
Ethernet19        28            10000        18        0        none
Ethernet20        29            10000        19        0        none
Ethernet21        26            10000        20        0        none
Ethernet22        27            10000        21        0        none
Ethernet23        24            10000        22        0        none
Ethernet24        25            10000        23        0        none
Ethernet25        0,1,2,3       100000       24        0        none
Ethernet29        4,5,6,7       100000       25        0        none
