obj-m := x86-64-asterfusion-cx532p-n_fl00e02.o
x86-64-asterfusion-cx532p-n_fl00e02-objs := x86-64-asterfusion-cx532p-n-common.o x86-64-asterfusion-cx532p-n-sys.o \
x86-64-asterfusion-cx532p-n-eeprom.o x86-64-asterfusion-cx532p-n-fan.o x86-64-asterfusion-cx532p-n-power.o \
x86-64-asterfusion-cx532p-n-thermal.o x86-64-asterfusion-cx532p-n-qsfp.o
