# Asterfusion CX532P-N platform modules

ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE_VERSION = 1.0.0
ASTERFUSION_CX532P-N_PLATFORM_MODULE_VERSION = 1.0.0
export ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX532P-N_PLATFORM_MODULE_VERSION

ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE = sonic-platform-asterfusion-cx308p-48y-n_$(ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE_VERSION)_amd64.deb
$(ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx308p_48y_n-r0
$(ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-asterfusion
$(ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE)_DEPENDS +=  $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(ASTERFUSION_CX308P-48Y-N_PLATFORM_MODULE)

ASTERFUSION_CX532P-N_PLATFORM_MODULE = sonic-platform-asterfusion-cx532p-n_$(ASTERFUSION_CX532P-N_PLATFORM_MODULE_VERSION)_amd64.deb
$(ASTERFUSION_CX532P-N_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx532p_n-r0
$(ASTERFUSION_CX532P-N_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-asterfusion
$(ASTERFUSION_CX532P-N_PLATFORM_MODULE)_DEPENDS +=  $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(ASTERFUSION_CX532P-N_PLATFORM_MODULE)
