#!/bin/bash

if [ "$1" == "all" ]; then
    if [ -r /usr/local/bin/asterfusion_x204y_24gt_sensors.py ]; then
            sudo python /usr/local/bin/asterfusion_x204y_24gt_sensors.py show fans
            sudo python /usr/local/bin/asterfusion_x204y_24gt_sensors.py show temps
    fi
elif [ "$1" == "fans" ]; then
    sudo python /usr/local/bin/asterfusion_x204y_24gt_sensors.py show fans
elif [ "$1" == "temps" ]; then
    sudo python /usr/local/bin/asterfusion_x204y_24gt_sensors.py show temps
else
    echo "show environment [OPTIONS]"
    echo "OPTIONS:"
    echo "  all       Show system environment status"
    echo "  fans      Show system fans status"
    echo "  temps     Show system temps"
fi
