#!/bin/sh

mr_reboot() {
    sudo /sbin/reboot
}

if [ $# -eq 0 ] || [ $@ = "-p" ] || [ $@ = "--reboot" ] || [ $@ = "--poweroff" ] || [ $@ = "-f" ] || [ $@ = "--force" ];  then
    mr_reboot
elif [ $@ = "--halt" ]; then
    sudo halt
else
    echo "unsupported option"
fi

