#!/bin/sh

mr_reboot() {
    sudo /sbin/reboot
}

if [ $# -eq 0 ] || [ $@ = "-r" ] || [ $@ = "--reboot" ] || [ $@ = "-h" ] || [ $@ = "-P" ] || [ $@ = "--poweroff" ]; then
    mr_reboot
elif [ $@ = "-H" ] || [ $@ = "--halt" ]; then
    sudo halt
else
    echo "unsupported option"
fi

